#!/bin/bash
rm *.png
#
#-------------------------------
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:9 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+4+0 label1.png
convert -background none -fill white -font My-Font-Regular -pointsize 80 label:. -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 20x0+7+0 label3.png
convert -background none -fill white -font My-Font-Regular -pointsize 90 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 165x95+7+0 label4.png
convert -background none -gravity South label*.* +append 9900.png
rm label*.*
#-------------------------------
#convert -background none -fill '#f04040' -font My-Font-Regular -pointsize 112 label:1 -crop 65x130+0+0 label1.png
#convert -background none -fill '#f04040' -font My-Font-Regular -pointsize 112 label:0 -crop 65x130+2+0 label2.png
#convert -background none -fill '#f04040' -font My-Font-Regular -pointsize 80 label:. -crop 20x0+0+0 label3.png
#convert -background none -fill '#f04040' -font My-Font-Regular -pointsize 80 label:900 -crop 165x180+0+0 label4.png
#convert -background none -gravity South label*.* +append 004.png
#rm label*.*
#-------------------------------
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:8 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+4+0 label1.png
convert -background none -fill white -font My-Font-Regular -pointsize 80 label:. -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 20x0+7+0 label3.png
convert -background none -fill white -font My-Font-Regular -pointsize 90 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 165x95+7+0 label4.png
convert -background none -gravity South label*.* +append 8900.png
rm label*.*
#-------------------------------
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+4+0 label1.png
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:0 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 70x110+4+0 label2.png
convert -background none -fill white -font My-Font-Regular -pointsize 80 label:. -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 20x0+7+0 label3.png
convert -background none -fill white -font My-Font-Regular -pointsize 90 label:900 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 165x95+7+0 label4.png
convert -background none -gravity South label*.* +append 10900.png
rm label*.*
#-------------------------------
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:1 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 65x110+4+0 label1.png
convert -background none -fill white -font My-Font-Regular -pointsize 112 label:4 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 70x110+4+0 label2.png
convert -background none -fill white -font My-Font-Regular -pointsize 80 label:. -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 20x0+7+0 label3.png
convert -background none -fill white -font My-Font-Regular -pointsize 90 label:500 -trim \( +clone -background gray -shadow 100x4+0+0 \) +swap -background none -layers merge +repage -crop 165x95+7+0 label4.png
convert -background none -gravity South label*.* +append 14500.png
rm label*.*
#-------------------------------
